---
galaxy_info:
  author: Stephen Clayton
  description: Amazon Route53 DNS role for Satellite 6, that sets a DNS entry on Route53 for an installation on AWS
  # company: your company (optional)
  license: GPLv3
  min_ansible_version: 1.9.4
  platforms:
    - name: EL
      versions:
        - 6
        - 7
  categories:
    - cloud
    - cloud:ec2
    - packaging
    - system
dependencies: []