---
galaxy_info:
  author: Stephen Clayton
  description: Setup role for Satellite 6, that registers the system with Red Hat Subscription Management, enables products and adds repositories for consumption
  # company: your company (optional)
  license: GPLv3
  min_ansible_version: 1.9.4
  platforms:
    - name: EL
      versions:
        - 6
        - 7
  categories:
    - cloud
    - cloud:ec2
    - packaging
    - system
dependencies: []